Completed AI/ML section and started on Fundamentals Section
plotly/plotly.r-docs pull request #70
Opened 2021-08-05 17:06 UTC by kvdesai

Build is failing as of now.

2021-08-06 17:17 UTC, HammadTheOne commented
Nice to see the `anglr` install works! 

I'm seeing another minor issue with the build. Seems like it passed at one point, but there's another URL in one of the `.Rmd` that's timing out and causing the build to fail.

2021-08-06 17:50 UTC, kvdesai commented
Oh ok...will check

2021-08-06 18:35 UTC, kvdesai commented
Looks like the old R code has multiple pages downloading data directly from https://stats.idre.ucla.edu
That server seems to be down as of now, and hence the build is failing. I am guessing that this is a criticlal issue for UCLA and hence should get fixed soon. Let's wait for a day?

2021-08-06 20:15 UTC, kvdesai commented
The university portal https://stats.idre.ucla.edu is back up again, and hence the build is now passing. 
@HammadTheOne

2021-08-06 20:17 UTC, HammadTheOne commented
@kvdesai  Thanks for the update! This is the first time I've seen it happen, so it's fine for now, but if it becomes a recurring problem it might be worth locally storing and loading those datasets. It's out of the scope for this PR though, so we can come back to that if it becomes an issue.

2021-08-13 19:10 UTC, HammadTheOne commented on r/2021-07-27-ml-pca.rmd
> +    yaxis4=axis
Is there a better way to set multiple axes here? I was thinking maybe with subplots, but that seems just as verbose. We might just have to stick with this, but if you have any other ideas, it might be worth exploring them to make the code cleaner.

2021-08-13 19:10 UTC, HammadTheOne commented on r/2021-07-27-ml-pca.rmd
> +Now, we apply `PCA` the same dataset, and retrieve **all** the components. We use the same `splom` trace to display our results, but this time our features are the resulting *principal components*, o
```suggestion
Now, we apply `PCA` to the same dataset, and retrieve **all** the components. We use the same `splom` trace to display our results, but this time our features are the resulting *principal components*, ordered by how much variance they are able to explain.

```

2021-08-13 19:10 UTC, HammadTheOne commented on r/2021-07-27-ml-pca.rmd
> +      list(label='PC4', values=~PC4)
I think we'll want to use `lapply` here to clean up the code a little.

2021-08-13 19:10 UTC, HammadTheOne commented on r/2021-07-27-ml-pca.rmd
> +      title = "1"))
```suggestion
    plot_bgcolor='#e5ecf6',
    xaxis = list(
      title = "0",
      zerolinecolor = "#ffff",
      zerolinewidth = 2,
      gridcolor='#ffff'), 
    yaxis = list(
      title = "1",
      zerolinecolor = "#ffff",
      zerolinewidth = 2,
      gridcolor='#ffff'))
```

To add to this, I would add ` plot_bgcolor='#e5ecf6'` to any other plots on this page with that color. Reasoning being that with a white plot background on a white page, it's hard to tell where the plot canvas ends.

2021-08-13 19:10 UTC, HammadTheOne commented on r/2021-07-28-ml-tsne-umap.rmd
> +## t-SNE and UMAP projections in Python
```suggestion
## t-SNE and UMAP projections in R

```

2021-08-13 19:41 UTC, HammadTheOne commented on r/2021-07-28-ml-tsne-umap.rmd
> +Compared to a method like Principal Component Analysis (PCA), it takes significantly more time to converge, but present significantly better insights when visualized. For example, by projecting featu
The description here cuts off, both on the Python and R docs. We'll want to finish this off for the R ones at least.

2021-08-13 19:44 UTC, HammadTheOne commented on r/2021-07-28-ml-tsne-umap.rmd
> +fig <-  plot_ly(data = pdb ,x =  ~X1, y = ~X2, z = ~X3, color = ~iris$Species, colors = c('#636EFA','#EF553B','#00CC96') ) %>%
Same comment as earlier, I would add `bg_color` and `zerolinecolor` to the axes to match the Python figures..

2021-08-13 19:49 UTC, HammadTheOne commented on r/2021-08-02-styling-plotly-in-r.rmd
> +
:+1:

2021-08-13 20:04 UTC, HammadTheOne commented on r/2021-08-02-styling-plotly-in-r.rmd
> +fig
```suggestion
library(ggplot2)
library(plotly)

data(mpg)

base <- ggplot(mpg, aes(cty, hwy, color = factor(cyl))) +
  geom_jitter() + 
  geom_abline(colour = "grey50", size = 2)

labelled <- base +
  labs(
    x = "City mileage/gallon",
    y = "Highway mileage/gallon",
    colour = "Cylinders",
    title = "Highway and city mileage are highly correlated"
  ) +
  scale_colour_brewer(type = "seq", palette = "Spectral")

fig <- ggplotly(labelled)

fig

```

Just adding some spacing for readability.

2021-08-16 15:23 UTC, HammadTheOne commented on r/2021-08-03-horizontal-vertical-shapes.rmd
> +[Dash for R](https://dashr.plotly.com) is an open-source framework for building analytical applications, with no Javascript required, and it is tightly integrated with the Plotly graphing library.
We might need to check in with Nicolas here to see how we're going to embed these Dash apps directly into the docs for R. 

With the Python docs, we're using an IFrame, (https://github.com/plotly/plotly.py/blob/doc-prod/doc/python/horizontal-vertical-shapes.md)  which contains a link to the app hosted on the Dash Gallery server. We can maybe give you access to that or host the app there to have the same functionality here.

2021-08-16 15:25 UTC, HammadTheOne commented on r/2021-08-04-figure-labels.rmd
> +How to set the global font, title, legend-entries, and axis-titles in R.
```suggestion
How to set the global font, title, legend-entries, and axis-titles in for plots in R.

```

2021-08-16 15:26 UTC, HammadTheOne commented on r/2021-08-04-figure-labels.rmd
> +
Similar comment to previous examples, I would set the `plot_bgcolor` to `#e5ecf6` to match the Plotly Express default within the Python docs for visibility and aesthetics.

2021-08-16 15:30 UTC, HammadTheOne requested changes
Hi @kvdesai, this is some really good documentation - there's some great updates for the R specific features as well. 

I've left some comments and suggestions. I think we'll want to make the changes for the aesthetics and then we can consider some of the other ones to clean up the code a little bit. 

As far as integrating the Dash apps go, I think this is a good first step, but we'll want to eventually embed them directly into the docs through an iframe like the Python ones, but we can discuss that in more detail and come back to them once we have a plan in place.

Let me know if you have any questions about the feedback and feel free to ping me whenever the changes have been made.

2021-08-16 16:39 UTC, kvdesai commented on r/2021-07-27-ml-pca.rmd
> +    yaxis4=axis
Let me think about it.

2021-08-16 16:40 UTC, kvdesai commented on r/2021-07-27-ml-pca.rmd
> +      title = "1"))
Sure makes sense.

2021-08-16 16:45 UTC, kvdesai commented on r/2021-08-03-horizontal-vertical-shapes.rmd
> +[Dash for R](https://dashr.plotly.com) is an open-source framework for building analytical applications, with no Javascript required, and it is tightly integrated with the Plotly graphing library.
Sure; we can do that. Let me know once you have a chance to discuss with Nicolas and Jack.

2021-08-17 16:01 UTC, kvdesai commented on r/2021-08-04-figure-labels.rmd
> +
done

2021-08-17 16:02 UTC, kvdesai commented on r/2021-08-03-horizontal-vertical-shapes.rmd
> +[Dash for R](https://dashr.plotly.com) is an open-source framework for building analytical applications, with no Javascript required, and it is tightly integrated with the Plotly graphing library.
Sure Hammad, let's figure out the Dash piece once we have the pages live.

2021-08-17 16:02 UTC, kvdesai commented on r/2021-07-27-ml-pca.rmd
> +      list(label='PC4', values=~PC4)
as discuss, this isn't straightforward and results in less readable code. Ignoring for now.

2021-08-17 20:58 UTC, HammadTheOne approved these changes
:woman_dancing:

2021-08-17 20:59 UTC, merged